### PR TITLE
Adding intial files

### PR DESCRIPTION
**Pull request by nhhughes**
Prof. Barton, 
    Here's all the files I have, pretty much.  Most of the repo is under GPL V3.0, there are some files (drum and pam code) that I haven't licensed yet, mainly because I'm not sure where some of the example code comes from / how that works with arduino.

### CODE REVIEW

**Comment by scottbarton** [comment]
ok, I merged the pull request so now everything is in that repository.  So
going forward all the changes should be in that repo, correct?

On Thu, Feb 12, 2015 at 2:46 PM, Nathan Hughes notifications@github.com
wrote:

> Prof. Barton,
> Here's all the files I have, pretty much. Most of the repo is under GPL
> V3.0, there are some files (drum and pam code) that I haven't licensed yet,
> mainly because I'm not sure where some of the example code comes from / how
> that works with arduino.
> 
> ---
> 
> You can view, comment on, or merge this pull request online at:
> 
>   https://github.com/scottbarton/MPR-lab/pull/1
> 
> Commit Summary
> -   Initial commit
> -   for later work
> -   generate and process clients
> -   moved files around
> -   working sampling
> -   merge resolution
> -   fixed merge
> -   acf work began
> -   acf test for real
> -   working
> -   onset detection / timing added
> -   cleaned up repository
> -   Working Message Passing Examples
> -   made modified client and processing server
> -   compiling code
> -   everything working
> -   added oscpack dependency
> -   cleaned up repo
> -   finished cleaning up repo for now
> -   moved stuff around
> -   deleted modes?
> -   First push of sample code for testing the MultiSolenoidDriver Board
>   V1 or V1-1. Sequences through all solenoids and steps motor.
> -   some work on composition
> -   fleshed out most of the c-space classes
> -   most everything finished besides a couple of mapppings
> -   added some exporting tools
> -   forgot to add this file to the repo
> -   finished converter class
> -   finished c++ test version of scheduler
> -   added licenses
> -   fixed merge
> 
> File Changes
> -   A .ipynb_checkpoints/PlottingStuff-checkpoint.ipynb<
>   https://github.com/scottbarton/MPR-lab/pull/1/files#diff-0> (9)
> -   A Algorithmic_Composition_Tools/ToMidi.py<
>   https://github.com/scottbarton/MPR-lab/pull/1/files#diff-1> (32)
> -   A Algorithmic_Composition_Tools/ToWestern.py<
>   https://github.com/scottbarton/MPR-lab/pull/1/files#diff-2> (106)
> -   A Algorithmic_Composition_Tools/**init**.py<
>   https://github.com/scottbarton/MPR-lab/pull/1/files#diff-3> (21)
> -   A AudioAnalysis/PitchExploraiton.ipynb<
>   https://github.com/scottbarton/MPR-lab/pull/1/files#diff-4> (439)
> -   A AudioAnalysis/PlottingStuff.ipynb<
>   https://github.com/scottbarton/MPR-lab/pull/1/files#diff-5> (155)
> -   A AudioAnalysis/analysis.c<
>   https://github.com/scottbarton/MPR-lab/pull/1/files#diff-6> (98)
> -   A AudioAnalysis/mpr_processing_client.c<
>   https://github.com/scottbarton/MPR-lab/pull/1/files#diff-7> (166)
> -   A AudioAnalysis/mpr_processing_client_wmp.c<
>   https://github.com/scottbarton/MPR-lab/pull/1/files#diff-8> (246)
> -   A AudioAnalysis/note_generator.c<
>   https://github.com/scottbarton/MPR-lab/pull/1/files#diff-9> (163)
> -   A Composition_Workspace_Hughes/CSpaceLibrary/CSpaceSampler.py<
>   https://github.com/scottbarton/MPR-lab/pull/1/files#diff-10> (88)
> -   A Composition_Workspace_Hughes/CSpaceLibrary/CollisionChecker.py<
>   https://github.com/scottbarton/MPR-lab/pull/1/files#diff-11> (133)
> -   A Composition_Workspace_Hughes/CSpaceLibrary/Configuration.py<
>   https://github.com/scottbarton/MPR-lab/pull/1/files#diff-12> (51)
> -   A Composition_Workspace_Hughes/CSpaceLibrary/PathExporter.py<
>   https://github.com/scottbarton/MPR-lab/pull/1/files#diff-13> (42)
> -   A Composition_Workspace_Hughes/CSpaceLibrary/PathPlanner.py<
>   https://github.com/scottbarton/MPR-lab/pull/1/files#diff-14> (65)
> -   A Composition_Workspace_Hughes/CSpaceLibrary/**init**.py<
>   https://github.com/scottbarton/MPR-lab/pull/1/files#diff-15> (21)
> -   A Composition_Workspace_Hughes/MusicGenerator.py<
>   https://github.com/scottbarton/MPR-lab/pull/1/files#diff-16> (77)
> -   A Daughter_Control/perc_robot_code_basic/test.cc<
>   https://github.com/scottbarton/MPR-lab/pull/1/files#diff-17> (246)
> -   A MAX_MSP_MIDI_CONVERTER/empty<
>   https://github.com/scottbarton/MPR-lab/pull/1/files#diff-18> (0)
> -   A MISC_DOC/empty<
>   https://github.com/scottbarton/MPR-lab/pull/1/files#diff-19> (0)
> -   A Makefile<
>   https://github.com/scottbarton/MPR-lab/pull/1/files#diff-20> (54)
> -   A MessagePassing/client.c<
>   https://github.com/scottbarton/MPR-lab/pull/1/files#diff-21> (109)
> -   A MessagePassing/server.c<
>   https://github.com/scottbarton/MPR-lab/pull/1/files#diff-22> (99)
> -   A Mother_Control/empty<
>   https://github.com/scottbarton/MPR-lab/pull/1/files#diff-23> (0)
> -   A
>   MultiSolenoidDriverV1_TestCodeV1/MultiSolenoidDriverV1_TestCodeV1.ino<
>   https://github.com/scottbarton/MPR-lab/pull/1/files#diff-24> (114)
> -   A MultiSolenoidDriverV1_TestCodeV1/PinDef.h<
>   https://github.com/scottbarton/MPR-lab/pull/1/files#diff-25> (38)
> -   A PAM_CONTROL/PAM/PAM/.DS_Store<
>   https://github.com/scottbarton/MPR-lab/pull/1/files#diff-26> (0)
> -   A PAM_CONTROL/PAM/PAM/PAMCode-master/.DS_Store<
>   https://github.com/scottbarton/MPR-lab/pull/1/files#diff-27> (0)
> -   A PAM_CONTROL/PAM/PAM/PAMCode-master/sketch_mar20a/.DS_Store<
>   https://github.com/scottbarton/MPR-lab/pull/1/files#diff-28> (0)
> -   A PAM_CONTROL/PAM/PAM/PAMCode-master/sketch_mar20a/PAM.cpp<
>   https://github.com/scottbarton/MPR-lab/pull/1/files#diff-29> (376)
> -   A PAM_CONTROL/PAM/PAM/PAMCode-master/sketch_mar20a/PAM.h<
>   https://github.com/scottbarton/MPR-lab/pull/1/files#diff-30> (33)
> -   A
>   PAM_CONTROL/PAM/PAM/PAMCode-master/sketch_mar20a/PAM.xcworkspace/contents.xcworkspacedata<
>   https://github.com/scottbarton/MPR-lab/pull/1/files#diff-31> (13)
> -   A
>   PAM_CONTROL/PAM/PAM/PAMCode-master/sketch_mar20a/PAM.xcworkspace/xcuserdata/ecstipan.xcuserdatad/UserInterfaceState.xcuserstate<
>   https://github.com/scottbarton/MPR-lab/pull/1/files#diff-32> (0)
> -   A
>   PAM_CONTROL/PAM/PAM/PAMCode-master/sketch_mar20a/PAM.xcworkspace/xcuserdata/ecstipan.xcuserdatad/WorkspaceSettings.xcsettings<
>   https://github.com/scottbarton/MPR-lab/pull/1/files#diff-33> (20)
> -   A
>   PAM_CONTROL/PAM/PAM/PAMCode-master/sketch_mar20a/PAM.xcworkspace/xcuserdata/ecstipan.xcuserdatad/xcdebugger/Breakpoints.xcbkptlist<
>   https://github.com/scottbarton/MPR-lab/pull/1/files#diff-34> (5)
> -   A PAM_CONTROL/PAM/PAM/PAMCode-master/sketch_mar20a/sketch_mar20a.ino<
>   https://github.com/scottbarton/MPR-lab/pull/1/files#diff-35> (2)
> -   A PAM_CONTROL/PAM/PAM/PAM_code/PAM_code.ino<
>   https://github.com/scottbarton/MPR-lab/pull/1/files#diff-36> (87)
> -   A PAM_CONTROL/PAM/PAM/PAM_code_2/PAM_code_2.ino<
>   https://github.com/scottbarton/MPR-lab/pull/1/files#diff-37> (103)
> -   A PAM_CONTROL/PAM/PAM/PAM_code_3/.DS_Store<
>   https://github.com/scottbarton/MPR-lab/pull/1/files#diff-38> (0)
> -   A PAM_CONTROL/PAM/PAM/PAM_code_3/PAM_code_3.ino<
>   https://github.com/scottbarton/MPR-lab/pull/1/files#diff-39> (184)
> -   A PAM_CONTROL/PAM/PAM/PAM_code_4/PAM_code_4.ino<
>   https://github.com/scottbarton/MPR-lab/pull/1/files#diff-40> (200)
> -   A PAM_CONTROL/PAM/PAM/PAM_code_5/PAM_code_5.ino<
>   https://github.com/scottbarton/MPR-lab/pull/1/files#diff-41> (180)
> -   A
>   PAM_CONTROL/PAM/PAM/Stepper_Motor_AccelStepper/Stepper_Motor_AccelStepper.ino<
>   https://github.com/scottbarton/MPR-lab/pull/1/files#diff-42> (26)
> -   A
>   PAM_CONTROL/PAM/PAM/Stepper_Motor_stepper/stepper_motor/stepper_motor.ino<
>   https://github.com/scottbarton/MPR-lab/pull/1/files#diff-43> (13)
> -   A PAM_CONTROL/PAM/PAM/Stepper_Motor_stepperDriver/.DS_Store<
>   https://github.com/scottbarton/MPR-lab/pull/1/files#diff-44> (0)
> -   A
>   PAM_CONTROL/PAM/PAM/Stepper_Motor_stepperDriver/Stepper_Motor_stepperDriver.ino<
>   https://github.com/scottbarton/MPR-lab/pull/1/files#diff-45> (19)
> -   A PAM_CONTROL/PAM/PAM/stepper_motor_basic/stepper_motor_basic.ino<
>   https://github.com/scottbarton/MPR-lab/pull/1/files#diff-46> (20)
> -   A
>   PAM_CONTROL/PAM/PAM/stepper_motor_interrupts/stepper_motor_interrupts.ino<
>   https://github.com/scottbarton/MPR-lab/pull/1/files#diff-47> (60)
> -   A PAM_CONTROL/PAM/__MACOSX/PAM/._.DS_Store<
>   https://github.com/scottbarton/MPR-lab/pull/1/files#diff-48> (0)
> -   A PAM_CONTROL/PAM/__MACOSX/PAM/PAMCode-master/._.DS_Store<
>   https://github.com/scottbarton/MPR-lab/pull/1/files#diff-49> (0)
> -   A
>   PAM_CONTROL/PAM/__MACOSX/PAM/PAMCode-master/sketch_mar20a/._.DS_Store<
>   https://github.com/scottbarton/MPR-lab/pull/1/files#diff-50> (0)
> -   A PAM_CONTROL/PAM/__MACOSX/PAM/PAMCode-master/sketch_mar20a/._PAM.h<
>   https://github.com/scottbarton/MPR-lab/pull/1/files#diff-51> (0)
> -   A
>   PAM_CONTROL/PAM/__MACOSX/PAM/PAMCode-master/sketch_mar20a/._PAM.xcworkspace<
>   https://github.com/scottbarton/MPR-lab/pull/1/files#diff-52> (0)
> -   A
>   PAM_CONTROL/PAM/__MACOSX/PAM/PAMCode-master/sketch_mar20a/PAM.xcworkspace/._contents.xcworkspacedata<
>   https://github.com/scottbarton/MPR-lab/pull/1/files#diff-53> (0)
> -   A
>   PAM_CONTROL/PAM/__MACOSX/PAM/PAMCode-master/sketch_mar20a/PAM.xcworkspace/._xcuserdata<
>   https://github.com/scottbarton/MPR-lab/pull/1/files#diff-54> (0)
> -   A
>   PAM_CONTROL/PAM/__MACOSX/PAM/PAMCode-master/sketch_mar20a/PAM.xcworkspace/xcuserdata/._ecstipan.xcuserdatad<
>   https://github.com/scottbarton/MPR-lab/pull/1/files#diff-55> (0)
> -   A
>   PAM_CONTROL/PAM/__MACOSX/PAM/PAMCode-master/sketch_mar20a/PAM.xcworkspace/xcuserdata/ecstipan.xcuserdatad/._UserInterfaceState.xcuserstate<
>   https://github.com/scottbarton/MPR-lab/pull/1/files#diff-56> (0)
> -   A
>   PAM_CONTROL/PAM/__MACOSX/PAM/PAMCode-master/sketch_mar20a/PAM.xcworkspace/xcuserdata/ecstipan.xcuserdatad/._WorkspaceSettings.xcsettings<
>   https://github.com/scottbarton/MPR-lab/pull/1/files#diff-57> (0)
> -   A
>   PAM_CONTROL/PAM/__MACOSX/PAM/PAMCode-master/sketch_mar20a/PAM.xcworkspace/xcuserdata/ecstipan.xcuserdatad/._xcdebugger<
>   https://github.com/scottbarton/MPR-lab/pull/1/files#diff-58> (0)
> -   A
>   PAM_CONTROL/PAM/__MACOSX/PAM/PAMCode-master/sketch_mar20a/PAM.xcworkspace/xcuserdata/ecstipan.xcuserdatad/xcdebugger/._Breakpoints.xcbkptlist<
>   https://github.com/scottbarton/MPR-lab/pull/1/files#diff-59> (0)
> -   A PAM_CONTROL/PAM/__MACOSX/PAM/PAM_code_3/._.DS_Store<
>   https://github.com/scottbarton/MPR-lab/pull/1/files#diff-60> (0)
> -   A
>   PAM_CONTROL/PAM/__MACOSX/PAM/Stepper_Motor_stepperDriver/._.DS_Store<
>   https://github.com/scottbarton/MPR-lab/pull/1/files#diff-61> (0)
> -   A PERCUSSION_CONTROL/perc_robot/.DS_Store<
>   https://github.com/scottbarton/MPR-lab/pull/1/files#diff-62> (0)
> -   A PERCUSSION_CONTROL/perc_robot/M3-Base-OS<
>   https://github.com/scottbarton/MPR-lab/pull/1/files#diff-63> (1)
> -   A
>   PERCUSSION_CONTROL/perc_robot/perc_arms_interrupts/perc_arms_interrupts.ino<
>   https://github.com/scottbarton/MPR-lab/pull/1/files#diff-64> (72)
> -   A PERCUSSION_CONTROL/perc_robot/perc_robot_basic_serial/.DS_Store<
>   https://github.com/scottbarton/MPR-lab/pull/1/files#diff-65> (0)
> -   A
>   PERCUSSION_CONTROL/perc_robot/perc_robot_basic_serial/perc_robot_basic_serial.ino<
>   https://github.com/scottbarton/MPR-lab/pull/1/files#diff-66> (26)
> -   A
>   PERCUSSION_CONTROL/perc_robot/perc_robot_basic_serial_2/perc_robot_basic_serial_2.ino<
>   https://github.com/scottbarton/MPR-lab/pull/1/files#diff-67> (88)
> -   A
>   PERCUSSION_CONTROL/perc_robot/perc_robot_basic_serial_test/perc_robot_basic_serial_test.ino<
>   https://github.com/scottbarton/MPR-lab/pull/1/files#diff-68> (16)
> -   A PERCUSSION_CONTROL/perc_robot/perc_robot_code/perc_robot_code.ino<
>   https://github.com/scottbarton/MPR-lab/pull/1/files#diff-69> (66)
> -   A PERCUSSION_CONTROL/perc_robot/perc_robot_code_2/MIDI.cpp<
>   https://github.com/scottbarton/MPR-lab/pull/1/files#diff-70> (1162)
> -   A PERCUSSION_CONTROL/perc_robot/perc_robot_code_2/MIDI.h<
>   https://github.com/scottbarton/MPR-lab/pull/1/files#diff-71> (315)
> -   A
>   PERCUSSION_CONTROL/perc_robot/perc_robot_code_2/perc_robot_code_2.ino<
>   https://github.com/scottbarton/MPR-lab/pull/1/files#diff-72> (72)
> -   A
>   PERCUSSION_CONTROL/perc_robot/perc_robot_code_2_2/perc_robot_code_2_2.ino<
>   https://github.com/scottbarton/MPR-lab/pull/1/files#diff-73> (73)
> -   A
>   PERCUSSION_CONTROL/perc_robot/perc_robot_code_3/perc_robot_code_3.ino<
>   https://github.com/scottbarton/MPR-lab/pull/1/files#diff-74> (110)
> -   A PERCUSSION_CONTROL/perc_robot/perc_robot_code_basic.zip<
>   https://github.com/scottbarton/MPR-lab/pull/1/files#diff-75> (0)
> -   A PERCUSSION_CONTROL/perc_robot/perc_robot_code_basic/.DS_Store<
>   https://github.com/scottbarton/MPR-lab/pull/1/files#diff-76> (0)
> -   A
>   PERCUSSION_CONTROL/perc_robot/perc_robot_code_basic/perc_robot_code_basic.ino<
>   https://github.com/scottbarton/MPR-lab/pull/1/files#diff-77> (74)
> -   M README.md<
>   https://github.com/scottbarton/MPR-lab/pull/1/files#diff-78> (59)
> -   A SharedMemoryTest/test1.cpp<
>   https://github.com/scottbarton/MPR-lab/pull/1/files#diff-79> (44)
> -   A SharedMemoryTest/test2.cpp<
>   https://github.com/scottbarton/MPR-lab/pull/1/files#diff-80> (41)
> -   A build/analysis_ap<
>   https://github.com/scottbarton/MPR-lab/pull/1/files#diff-81> (0)
> -   A build/child_sm<
>   https://github.com/scottbarton/MPR-lab/pull/1/files#diff-82> (0)
> -   A build/client_mp<
>   https://github.com/scottbarton/MPR-lab/pull/1/files#diff-83> (0)
> -   A build/parent_sm<
>   https://github.com/scottbarton/MPR-lab/pull/1/files#diff-84> (0)
> -   A build/server_mp<
>   https://github.com/scottbarton/MPR-lab/pull/1/files#diff-85> (0)
> -   A build/tone_gen_ap<
>   https://github.com/scottbarton/MPR-lab/pull/1/files#diff-86> (0)
> 
> Patch Links:
> -   https://github.com/scottbarton/MPR-lab/pull/1.patch
> -   https://github.com/scottbarton/MPR-lab/pull/1.diff
> 
> —
> Reply to this email directly or view it on GitHub<
> https://github.com/scottbarton/MPR-lab/pull/1>.

## 

Scott Barton, Ph.D.
Assistant Professor of Music
Worcester Polytechnic Institute
Director of the Music, Perception and Robotics Lab
http://www.scottbarton.info | twitter https://twitter.com/scottbartonmusi |
soundcloud https://soundcloud.com/scottbarton

**Comment by nhhughes** [comment]
Sorta.  Because I (and anyone else besides you) don't have write access to the repository, I have a forked version of the repository.  I can make changes in there, and whenever I want you to incorporate the changes I've made, I'd pull request those change into the repository that you have control of.  So going forward, all of the changes will be made in forked repositories, and then you'll select changes that you want to incorporate (based on pull requests from the forked repositories).

**Comment by scottbarton** [comment]
I will make you a collaborator then, which should work, correct?  Which
Nathan Hughes are you?

On Fri, Feb 13, 2015 at 11:25 AM, Nathan Hughes notifications@github.com
wrote:

> Sorta. Because I (and anyone else besides you) don't have write access to
> the repository, I have a forked version of the repository. I can make
> changes in there, and whenever I want you to incorporate the changes I've
> made, I'd pull request those change into the repository that you have
> control of. So going forward, all of the changes will be made in forked
> repositories, and then you'll select changes that you want to incorporate
> (based on pull requests from the forked repositories).
> 
> —
> Reply to this email directly or view it on GitHub<
> https://github.com/scottbarton/MPR-lab/pull/1#issuecomment-74280794>.

## 

Scott Barton, Ph.D.
Assistant Professor of Music
Worcester Polytechnic Institute
Director of the Music, Perception and Robotics Lab
http://www.scottbarton.info | twitter https://twitter.com/scottbartonmusi |
soundcloud https://soundcloud.com/scottbarton

**Comment by scottbarton** [comment]
I just added you - see if that works

On Fri, Feb 13, 2015 at 11:25 AM, Nathan Hughes notifications@github.com
wrote:

> Sorta. Because I (and anyone else besides you) don't have write access to
> the repository, I have a forked version of the repository. I can make
> changes in there, and whenever I want you to incorporate the changes I've
> made, I'd pull request those change into the repository that you have
> control of. So going forward, all of the changes will be made in forked
> repositories, and then you'll select changes that you want to incorporate
> (based on pull requests from the forked repositories).
> 
> —
> Reply to this email directly or view it on GitHub<
> https://github.com/scottbarton/MPR-lab/pull/1#issuecomment-74280794>.

## 

Scott Barton, Ph.D.
Assistant Professor of Music
Worcester Polytechnic Institute
Director of the Music, Perception and Robotics Lab
http://www.scottbarton.info | twitter https://twitter.com/scottbartonmusi |
soundcloud https://soundcloud.com/scottbarton

**Pull request merged**
